// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sztuntttrvrkqfethtyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6dHVudHR0cnZya3FmZXRodHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzE0NzUsImV4cCI6MjA2NDg0NzQ3NX0.rKwDl4gyfHQb4y8SiOcal8NmFOQZXAf0mQZ7GEdVjZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);